# Generated by Django 3.0.8 on 2020-10-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('event_city', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_start', models.DateTimeField(max_length=200)),
                ('event_end', models.DateTimeField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('all_day', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
                ('mentor_list', models.ManyToManyField(related_name='event_attending', related_query_name='mentor_attending', to='mentors.MentorProfile')),
            ],
        ),
    ]
