# Generated by Django 3.0.8 on 2020-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_city', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_start', models.DateTimeField(max_length=200)),
                ('event_end', models.DateTimeField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
            ],
        ),
    ]
