# Generated by Django 3.0.8 on 2020-11-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201102_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('needsAction', 'Needs Action'), ('D', 'Declined'), ('T', 'Tentative'), ('A', 'Accepted')], max_length=20),
        ),
    ]
