# Generated by Django 3.0.8 on 2020-11-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201031_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
