# Generated by Django 3.0.8 on 2020-10-26 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=200)),
                ('mentor_email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('mentor_type', models.CharField(max_length=200)),
                ('one_day_workshop', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MentorProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_one', models.BooleanField()),
                ('step_two', models.BooleanField()),
                ('step_three', models.BooleanField()),
                ('step_four', models.BooleanField()),
                ('step_five', models.BooleanField()),
                ('step_six', models.BooleanField()),
                ('step_seven', models.BooleanField()),
                ('step_eight', models.BooleanField()),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='mentors.MentorProfile')),
            ],
        ),
    ]
