# Generated by Django 3.0.8 on 2020-10-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_one', models.BooleanField()),
                ('step_two', models.BooleanField()),
                ('step_three', models.BooleanField()),
                ('step_four', models.BooleanField()),
                ('step_five', models.BooleanField()),
                ('step_six', models.BooleanField()),
                ('step_seven', models.BooleanField()),
                ('step_eight', models.BooleanField()),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='mentors.MentorProfile')),
            ],
        ),
    ]
