# Generated by Django 3.0.8 on 2020-10-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20201031_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprocess',
            name='calendar_invites_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='feedback_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='interview_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='offboarding_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='offer_position_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='onboarding_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='send_contract_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprocess',
            name='signed_contract_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
