# Generated by Django 3.0.8 on 2020-10-28 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentorprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprocess',
            name='mentor_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mentors.MentorProfile'),
        ),
    ]
